apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-deployment
spec:
  selector:
    matchLabels:
      app: es-server
  replicas: 1
  template:
    metadata:
      labels:
        app: es-server
    spec:
      containers:
      - name: es-container
        image: gcr.io/burner-panagnih/mock-es:v1
        ports:
          - containerPort: 8500

