apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-deployment
  labels:
    app: mock-es
spec:
  selector:
    matchLabels:
      app: mock-es
  replicas: 1
  template:
    metadata:
      labels:
        app: mock-es
    spec:
      containers:
      - name: mock-es
        image: gcr.io/burner-panagnih/mock-es:v1
        ports:
          - containerPort: 8500

